---
- name: Configure logging directory
  lineinfile:
    path: "{{ solr_home }}/log4j.properties"
    regexp: "^solr\\.log="
    line: solr.log=/var/log/solr
    state: present
  notify: restart solr

- name: Create Solr core conf dir
  file: >-
    path={{ solr_home }}/data/{{ item }}/conf
    state=directory mode=0755 owner=solr group=solr
  with_items: "{{ solr_cores }}"

- name: Copy solr schema file
  action: >-
    copy src={{ item }}/home/solr/ckan/conf/schema.xml
    dest={{ solr_home }}/data/{{ item }}/conf/schema.xml
    mode=0644
    force=yes
  with_items: "{{ solr_cores }}"
  notify: restart solr

- name: Copy solrconfig.xml on master solr
  template:
    src: solrconfig-master.xml.j2
    dest: "{{ solr_home }}/data/{{ item }}/conf/solrconfig.xml"
    force: true
    mode: 0644
  when: not is_solr_replica
  notify: restart solr
  with_items: "{{ solr_cores }}"

- name: Copy solrconfig.xml on replica solr
  template:
    src: solrconfig-replica.xml.j2
    dest: "{{ solr_home }}/data/{{ item }}/conf/solrconfig.xml"
    force: true
    mode: 0644
  when: is_solr_replica
  notify: restart solr
  with_items: "{{ solr_cores }}"
