---
- name: Remove tomcat6
  apt: name=tomcat6 state=absent

- name: Create Solr home dir
  file: >-
    path={{ solr_home_dir }}/{{ app_type }}/conf
    state=directory mode=0755 owner=solr group=solr

- name: copy solr schema file
  action: >-
    copy src={{app_type}}/home/solr/ckan/conf/schema.xml
    dest={{ solr_home_dir }}/{{ app_type }}/conf/schema.xml
    mode=0644
    force=yes
  notify: restart solr

- name: Copy solrconfig.xml on master solr
  template:
    src: solrconfig-master.xml.j2
    dest: "{{ solr_home_dir }}/{{ app_type }}/conf/solrconfig.xml"
    force: true
    mode: 0644
  when: not is_solr_replica
  notify: restart solr

- name: Copy solrconfig.xml on replica solr
  template:
    src: solrconfig-replica.xml.j2
    dest: "{{ solr_home_dir }}/{{ app_type }}/conf/solrconfig.xml"
    force: true
    mode: 0644
  when: is_solr_replica
  notify: restart solr
