---
- name: Remove tomcat6
  apt: name=tomcat6 state=absent

- name: Create Solr core conf dir
  file: >-
    path={{ solr_core_dir }}/conf
    state=directory mode=0755 owner=solr group=solr

- name: copy solr schema file
  action: >-
    copy src={{app_type}}/home/solr/ckan/conf/schema.xml
    dest={{ solr_core_dir }}/conf/schema.xml
    mode=0644
    force=yes
  notify: restart solr

- name: Copy solrconfig.xml on master solr
  template:
    src: solrconfig-master.xml.j2
    dest: "{{ solr_core_dir }}/conf/solrconfig.xml"
    force: true
    mode: 0644
  when: not is_solr_replica
  notify: restart solr

- name: Copy solrconfig.xml on replica solr
  template:
    src: solrconfig-replica.xml.j2
    dest: "{{ solr_core_dir }}/conf/solrconfig.xml"
    force: true
    mode: 0644
  when: is_solr_replica
  notify: restart solr

# For solr <5, we have to create the core via API
# - name: Add the new core
#   shell: "curl 'http://127.0.0.1:{{ solr_port }}/solr/admin/cores?\
#           action=CREATE&name={{app_type}}&\
#           instanceDir={{ solr_core_dir }}&\
#           config={{ solr_core_dir }}/conf/solrconfig.xml&\
#           schema={{ solr_core_dir }}/conf/schema.xml&\
#           dataDir={{ solr_core_dir }}'"
#   notify: restart solr
#   tags:
#     - skip_ansible_lint
