---
- name: set facts
  set_fact:
    is_solr4: "{{ solr_version.split('.')[0] == '4' }}"

# TODO once solr is upgraded and re-indexed, tomcat can be removed
# - name: Remove tomcat6
#   apt: name=tomcat6 state=absent

- name: Create logging directory
  file: dest=/var/log/solr state=directory owner=solr group=solr mode=0755

- include_tasks: configure-pre5.yml
  when: is_solr4

- include_tasks: configure.yml
  when: not is_solr4
