---
test-molecule-job: &test-molecule-job
  docker:
    - image: circleci/python:3.6
  environment:
    PIPENV_VENV_IN_PROJECT: 1
  # dir name must match molecule role
  working_directory: ~/datagov-deploy-solr
  steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        keys:
          - v1-pip-{{ checksum "Pipfile.lock" }}
          - v1-pip-
    - run: |
        pip install --user --upgrade pipenv
        make setup
    - save_cache:
        key: v1-pip-{{ checksum "Pipfile.lock" }}
        paths:
          - .venv
    - run: make test-$SCENARIO


version: 2
jobs:
  test-default:
    <<: *test-molecule-job
    environment:
      SCENARIO: default

  test-replication:
    <<: *test-molecule-job
    environment:
      SCENARIO: replication

workflows:
  version: 2
  commit:
    jobs:
      - test-default
      - test-replication
