---
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/datagov-deploy-solr # dir name must match molecule role
    steps:
      - checkout
      - run: make setup
      - run: make test
