---
test-molecule-job: &test-molecule-job
  machine: true
  # dir name must match molecule role
  working_directory: ~/datagov-deploy-solr
  steps:
    - checkout
    - run: make setup
    - run: make test-$SCENARIO


version: 2
jobs:
  test-default:
    <<: *test-molecule-job
    environment:
      SCENARIO: default

  test-replication:
    <<: *test-molecule-job
    environment:
      SCENARIO: replication

workflows:
  version: 2
  commit:
    jobs:
      - test-default
      - test-replication
