---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: solr-default
    image: ubuntu:trusty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  inventory:
    group_vars:
      all:
        solr_version: '5.5.5'
        solr_cores:
          - catalog
          - inventory
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
