---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: solr-default-bionic
    image: ubuntu:bionic
    groups:
      - bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  inventory:
    group_vars:
      all:
        solr_version: '6.6.6'
        solr_cores:
          - catalog
          - catalog-next
          - inventory
          - inventory-next
      bionic:
        java_packages:
          - openjdk-8-jdk
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
