---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: solr-catalog
    image: ubuntu:trusty
    groups:
      - solr
      - catalog-web
  - name: solr-inventory
    image: ubuntu:trusty
    groups:
      - solr
      - inventory-web
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
