---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: solr-master
    image: ubuntu:trusty
  - name: solr-replica
    image: ubuntu:trusty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  inventory:
    group_vars:
      all:
        solr_version: '5.5.5'
        solr_cores:
          - catalog
        # the docker containers don't actually talk to
        # each other, so this is just to confirm the
        # configuration.
        solr_master_server: solr-master
    host_vars:
      solr-replica:
        is_solr_replica: true
scenario:
  name: replication
verifier:
  name: testinfra
  lint:
    name: flake8
